### ISSUE TITLE
Monthly and Yearly - Only displaying current

### ISSUE THREAD

**Issue by syntaxerror** [arastta/android#4]
The app is actually only loading data from the current day, month and year.

Thus Monthly and Yearly becomes quite confusing, and also the usefulness of the app gets somewhat ...

Anyhow, when it is as it is, the texts should be changed:
Monthly -> This Month
Yearly -> This Year

**Comment by denisdulici** [comment]
This has been fixed 1.1 version Rune, feel free to update 😉

**Comment by syntaxerror** [comment]
Great, but the Norwegian language sucks. ;)

'I Dag' should be 'I dag'
'I Måned' should be 'Denne måned'
'I År' should be  'I år'

Already changed them at Crowdin when posting this issue, so if language file from there was used it would be great.

**Comment by denisdulici** [comment]
I've upload the new language file to Crowdin, will commit here after you finish the translation ;)

**Comment by syntaxerror** [comment]
Done, thanks. ;)
